export const ActionType = {
  FETCH_LOGIN_INFORMATION: "FETCH_LOGIN_INFORMATION",
  FETCH_LOGIN: "FETCH_LOGIN",
  FETCH_PUSH_TOKEN: "FETCH_PUSH_TOKEN",

  FETCH_NEW_TICKET_COUNT: "FETCH_NEW_TICKET_COUNT",
  FETCH_ASSIGNED_COUNT: "FETCH_ASSIGNED_COUNT",
  FETCH_ASSIST_COUNT: "FETCH_ASSIST_COUNT",
  FETCH_ONHOLD_COUNT: "FETCH_ONHOLD_COUNT",
  FTECH_VERIFY_FOR_COUNT: "FTECH_VERIFY_FOR_COUNT",
  FETCH_TODAY_COMPLETED_COUNT: "FETCH_TODAY_COMPLETED_COUNT",

  GET_DASHBOARD_ACTION: "GET_DASHBOARD_ACTION",

  FETCH_NOT_ASSIGNED_COMP_LIST_DEPT: "FETCH_NOT_ASSIGNED_COMP_LIST_DEPT",
  FETCH_ASSIGNED_COMP_USER: "FETCH_ASSIGNED_COMP_USER",
  FETCH_ASSIT_COMP_USER: "FETCH_ASSIT_COMP_USER",
  FETCH_ALL_COMPLAINT_TODAY: "FETCH_ALL_COMPLAINT_TODAY",
  FETCH_ONHOLD_COMPLAINT: "FETCH_ONHOLD_COMPLAINT",
  FETCH_FOR_VERIFY_COMP: "FETCH_FOR_VERIFY_COMP"

};
