export const ActionType = {
  FETCH_LOGIN_INFORMATION: "FETCH_LOGIN_INFORMATION",
  FETCH_LOGIN: "FETCH_LOGIN",
  FETCH_PUSH_TOKEN: "FETCH_PUSH_TOKEN",

  FETCH_NEW_TICKET_COUNT: "FETCH_NEW_TICKET_COUNT",
  FETCH_ASSIGNED_COUNT: "FETCH_ASSIGNED_COUNT",
  FETCH_ASSIST_COUNT: "FETCH_ASSIST_COUNT",
  FETCH_ONHOLD_COUNT: "FETCH_ONHOLD_COUNT",
  FTECH_VERIFY_FOR_COUNT: "FTECH_VERIFY_FOR_COUNT",
  FETCH_TODAY_COMPLETED_COUNT: "FETCH_TODAY_COMPLETED_COUNT",

  GET_DASHBOARD_ACTION: "GET_DASHBOARD_ACTION",

  FETCH_NOT_ASSIGNED_COMP_LIST_DEPT: "FETCH_NOT_ASSIGNED_COMP_LIST_DEPT",
  FETCH_ASSIGNED_COMP_USER: "FETCH_ASSIGNED_COMP_USER",
  FETCH_ASSIT_COMP_USER: "FETCH_ASSIT_COMP_USER",
  FETCH_ALL_COMPLAINT_TODAY: "FETCH_ALL_COMPLAINT_TODAY",
  FETCH_ONHOLD_COMPLAINT: "FETCH_ONHOLD_COMPLAINT",
  FETCH_FOR_VERIFY_COMP: "FETCH_FOR_VERIFY_COMP",
  FETCH_ON_PROGRESS_TICKET: "FETCH_ON_PROGRESS_TICKET",

  SHOW_OVERLAY_LOADING: "SHOW_OVERLAY_LOADING",
  FETCH_DEPT_EMP: "FETCH_DEPT_EMP",
  COMPLAINT_DEPT_NAME: "COMPLAINT_DEPT_NAME",
  FETCH_ACT_ASSIGN_EMP_LIST: "FETCH_ACT_ASSIGN_EMP_LIST",
  GET_MOBILE_APP_CRED: "GET_MOBILE_APP_CRED",

  GET_ASSIGNED_LIST_ONLY: "GET_ASSIGNED_LIST_ONLY",
  GET_ASSIGNED_FOR_VERIFY_LIST: "GET_ASSIGNED_FOR_VERIFY_LIST",


};
